Evaluate the 128G RCAs only if CMS is the collector for OldGen
opendistro-for-elasticsearch/performance-analyzer-rca pull request #482
Opened 2020-10-20 09:12 UTC by ktkrg

*Fixes #:*

*Description of changes:*
This change adds a new metric node(GC_Type) which tells what collector is used for a memory pool. The metric is used as a gating mechanism to proceed with the evaluation of the HighOldGenOccupancyRca and OldGenReclamationRca.

*Tests:*
UTs, tested on docker.

*If new tests are added, how long do the new ones take to complete*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-10-20 17:16 UTC, sidheart requested changes

2020-10-20 17:16 UTC, sidheart commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/rca/store/ElasticSearchAnalysisGraph.java
> +
nit: unnecessary

2020-10-20 17:16 UTC, sidheart commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/rca/store/ElasticSearchAnalysisGraph.java
> +
nit: unnecessary

2020-10-20 17:16 UTC, sidheart commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/rca/store/ElasticSearchAnalysisGraph.java
>      oldGenOccupancyRca.addAllUpstreams(Arrays.asList(heapMax, heapUsed));
Add gcType as an upstream

2020-10-20 17:16 UTC, sidheart commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/rca/store/ElasticSearchAnalysisGraph.java
>      oldGenReclamationRca.addAllUpstreams(Arrays.asList(heapUsed, heapMax, gcEvent));
Add gcType as an upstream

2020-10-20 17:20 UTC, ktkrg commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/rca/store/ElasticSearchAnalysisGraph.java
>      oldGenOccupancyRca.addAllUpstreams(Arrays.asList(heapMax, heapUsed));
good catch! Added.

2020-10-20 17:20 UTC, ktkrg commented on src/main/java/com/amazon/opendistro/elasticsearch/performanceanalyzer/rca/store/ElasticSearchAnalysisGraph.java
> +
removed

2020-10-21 20:28 UTC, sidheart submitted a review, later dismissed

2020-10-22 18:13 UTC, yojs approved these changes

2020-10-22 18:28 UTC, sidheart submitted a review, later dismissed

2020-10-22 18:31 UTC, yojs submitted a review, later dismissed

2020-10-22 20:43 UTC, yojs approved these changes

2020-10-22 20:44 UTC, sidheart approved these changes

2020-10-22 21:42 UTC, merged